name: UptadeZ Rising
version: 2.0
main: xyz.pikadev.pikarising.PikaRising
api-version: 1.16
authors: [ UptadeZ ]
description: UptadeZ Tarafından Tasarlanıp Yazılmıştır.
website: 
commands:
  başlat:
    description: Oyunu Başlatır
    usage: /başlat
    permissions:
      pikarising.start:
        description: Oyunu Başlatma Yetikisi
        default: op
